
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class frmMDI extends javax.swing.JFrame {

    /**
     * Creates new form frmMDI
     */
    
    
    /* Mendefenisikan Variabel admin*/
    private String Username = "admin";
    private String Password = "admin";
    
    
    
    
    public frmMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmMDI = new javax.swing.JDesktopPane();
        frmLogin = new javax.swing.JInternalFrame();
        PnlLogin = new javax.swing.JPanel();
        LblUsername = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        menuBar = new javax.swing.JMenuBar();
        MasterData = new javax.swing.JMenu();
        MenuBarang = new javax.swing.JMenuItem();
        MenuSupplier = new javax.swing.JMenuItem();
        Aplikasi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frmMDI.setBackground(new java.awt.Color(255, 255, 255));

        frmLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frmLogin.setNormalBounds(new java.awt.Rectangle(0, 0, 1020, 740));
        frmLogin.setVisible(true);

        PnlLogin.setBackground(new java.awt.Color(204, 204, 204));
        PnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trajan Pro", 0, 18))); // NOI18N

        LblUsername.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        LblUsername.setText("Username");

        LblPassword.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        LblPassword.setText("Password");

        BtnLogin.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlLoginLayout = new javax.swing.GroupLayout(PnlLogin);
        PnlLogin.setLayout(PnlLoginLayout);
        PnlLoginLayout.setHorizontalGroup(
            PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginLayout.createSequentialGroup()
                .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlLoginLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblUsername)
                            .addComponent(LblPassword))
                        .addGap(53, 53, 53)
                        .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(TxtPassword)))
                    .addGroup(PnlLoginLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(BtnLogin)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PnlLoginLayout.setVerticalGroup(
            PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblUsername))
                .addGap(31, 31, 31)
                .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPassword)
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(BtnLogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout frmLoginLayout = new javax.swing.GroupLayout(frmLogin.getContentPane());
        frmLogin.getContentPane().setLayout(frmLoginLayout);
        frmLoginLayout.setHorizontalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frmLoginLayout.setVerticalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frmMDI.add(frmLogin);
        frmLogin.setBounds(290, 200, 430, 280);

        MasterData.setText("Master Data");

        MenuBarang.setText("Barang");
        MenuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangActionPerformed(evt);
            }
        });
        MasterData.add(MenuBarang);

        MenuSupplier.setText("Supplier");
        MasterData.add(MenuSupplier);

        menuBar.add(MasterData);

        Aplikasi.setText("Aplikasi");
        menuBar.add(Aplikasi);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmMDI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmMDI, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        // TODO add your handling code here: 
        TxtUsername.requestFocus();

        if(!Username.equals(TxtUsername.getText()) && !Password.equals(TxtPassword.getText())){

            JOptionPane.showMessageDialog(null, "Username atau Password salah !!!");
            TxtUsername.setText("");
            TxtPassword.setText("");

        }
        else if(Username.equals(TxtUsername.getText()) && Password.equals(TxtPassword.getText())){

            PnlLogin.setVisible(false);
            frmLogin.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Username atau Password salah !!!");
            TxtUsername.setText("");
            TxtPassword.setText("");
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void MenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangActionPerformed
        // TODO add your handling code here:
        frmBarang frmBarang = new frmBarang();
        frmMDI.add(frmBarang);
        if(Username.equals(TxtUsername.getText()) && Password.equals(TxtPassword.getText())){
            MenuBarang.setEnabled(true);
            frmBarang.setVisible(true);    
        }
    }//GEN-LAST:event_MenuBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aplikasi;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JMenu MasterData;
    private javax.swing.JMenuItem MenuBarang;
    private javax.swing.JMenuItem MenuSupplier;
    private javax.swing.JPanel PnlLogin;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JInternalFrame frmLogin;
    private javax.swing.JDesktopPane frmMDI;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
