
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class frmMDI extends javax.swing.JFrame {

    /**
     * Creates new form frmMDI
     */
    final static String StringDriver = "com.mysql.jdbc.Driver";
    final static String StringConnection = "jdbc:mysql://localhost:3306/db_tokoenterprise?user=root&password=";


    
    
    public frmMDI() {
        super("Aplikasi Toko");
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("bg-apk4.jpg"));
        Image img = icon.getImage();
        frmMDI = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(img,0,0,getWidth(),
                    getHeight(),this);
            }
        };
        BtnSupplier = new javax.swing.JButton();
        BtnBarang = new javax.swing.JButton();
        BtnTransaksi = new javax.swing.JButton();
        PnlTokoPenjualan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MasterData = new javax.swing.JMenu();
        MenuBarang = new javax.swing.JMenuItem();
        MenuTransaksi = new javax.swing.JMenuItem();
        MenuSupplier = new javax.swing.JMenuItem();
        MenuCustomer = new javax.swing.JMenuItem();
        Aplikasi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1650, 1080));

        frmMDI.setBackground(new java.awt.Color(255, 255, 255));
        frmMDI.setForeground(new java.awt.Color(204, 204, 204));

        BtnSupplier.setBackground(new java.awt.Color(255, 153, 51));
        BtnSupplier.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        BtnSupplier.setText("SUPPLIER");
        BtnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupplierActionPerformed(evt);
            }
        });
        frmMDI.add(BtnSupplier);
        BtnSupplier.setBounds(30, 660, 320, 140);

        BtnBarang.setBackground(new java.awt.Color(51, 204, 255));
        BtnBarang.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        BtnBarang.setText("BARANG");
        BtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBarangActionPerformed(evt);
            }
        });
        frmMDI.add(BtnBarang);
        BtnBarang.setBounds(30, 210, 320, 140);

        BtnTransaksi.setBackground(new java.awt.Color(0, 204, 204));
        BtnTransaksi.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        BtnTransaksi.setText("TRANSAKSI");
        BtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransaksiActionPerformed(evt);
            }
        });
        frmMDI.add(BtnTransaksi);
        BtnTransaksi.setBounds(30, 430, 320, 140);

        PnlTokoPenjualan.setBackground(new java.awt.Color(240, 76, 92));
        PnlTokoPenjualan.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");

        javax.swing.GroupLayout PnlTokoPenjualanLayout = new javax.swing.GroupLayout(PnlTokoPenjualan);
        PnlTokoPenjualan.setLayout(PnlTokoPenjualanLayout);
        PnlTokoPenjualanLayout.setHorizontalGroup(
            PnlTokoPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTokoPenjualanLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(43, 43, 43))
        );
        PnlTokoPenjualanLayout.setVerticalGroup(
            PnlTokoPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTokoPenjualanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PnlTokoPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        frmMDI.add(PnlTokoPenjualan);
        PnlTokoPenjualan.setBounds(1510, 0, 360, 100);

        MasterData.setText("Master Data");

        MenuBarang.setText("Barang");
        MenuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangActionPerformed(evt);
            }
        });
        MasterData.add(MenuBarang);

        MenuTransaksi.setText("Transaksi");
        MenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTransaksiActionPerformed(evt);
            }
        });
        MasterData.add(MenuTransaksi);

        MenuSupplier.setText("Supplier");
        MenuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSupplierActionPerformed(evt);
            }
        });
        MasterData.add(MenuSupplier);

        MenuCustomer.setText("Customer");
        MenuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCustomerActionPerformed(evt);
            }
        });
        MasterData.add(MenuCustomer);

        menuBar.add(MasterData);

        Aplikasi.setText("Aplikasi");

        jMenuItem1.setText("Inventori Barang");
        Aplikasi.add(jMenuItem1);

        jMenu2.setText("Export");

        jMenuItem2.setText("Transaksi Penjualan");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Barang");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Supplier");
        jMenu2.add(jMenuItem4);

        Aplikasi.add(jMenu2);

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        Aplikasi.add(MenuExit);

        menuBar.add(Aplikasi);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmMDI, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmMDI, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void MenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangActionPerformed
        // TODO add your handling code here:
       try {
            frmBarang frmBarang = new frmBarang();
        frmMDI.add(frmBarang);
        frmBarang.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error cari tahu sendiri!");
        }    
        
    }//GEN-LAST:event_MenuBarangActionPerformed

    private void MenuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSupplierActionPerformed
        // TODO add your handling code here:
        frmSupplier frmSupplier = new frmSupplier();
        frmMDI.add(frmSupplier);
        frmSupplier.setVisible(true);    
        
    }//GEN-LAST:event_MenuSupplierActionPerformed

    private void MenuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCustomerActionPerformed
        // TODO add your handling code here:
         try{
             frmCustomer frmCustomer = new frmCustomer();
             frmMDI.add(frmCustomer);
             frmCustomer.setVisible(true);
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Error");
         }

    }//GEN-LAST:event_MenuCustomerActionPerformed

    private void MenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTransaksiActionPerformed
        // TODO add your handling code here:
        frmTransaksi frmTransaksi = new frmTransaksi();
        frmMDI.add(frmTransaksi);
        frmTransaksi.setVisible(true);    
    }//GEN-LAST:event_MenuTransaksiActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void BtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBarangActionPerformed
        // TODO add your handling code here:
        try {
            frmBarang frmBarang = new frmBarang();
        frmMDI.add(frmBarang);
        frmBarang.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error cari tahu sendiri!");
        } 
    }//GEN-LAST:event_BtnBarangActionPerformed

    private void BtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransaksiActionPerformed
        // TODO add your handling code here:
        frmTransaksi frmTransaksi = new frmTransaksi();
        frmMDI.add(frmTransaksi);
        frmTransaksi.setVisible(true);    
         
    }//GEN-LAST:event_BtnTransaksiActionPerformed

    private void BtnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupplierActionPerformed
        // TODO add your handling code here:
        frmSupplier frmSupplier = new frmSupplier();
        frmMDI.add(frmSupplier);
        frmSupplier.setVisible(true);    
        
    }//GEN-LAST:event_BtnSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aplikasi;
    private javax.swing.JButton BtnBarang;
    private javax.swing.JButton BtnSupplier;
    private javax.swing.JButton BtnTransaksi;
    private javax.swing.JMenu MasterData;
    private javax.swing.JMenuItem MenuBarang;
    private javax.swing.JMenuItem MenuCustomer;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuSupplier;
    private javax.swing.JMenuItem MenuTransaksi;
    private javax.swing.JPanel PnlTokoPenjualan;
    private javax.swing.JDesktopPane frmMDI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
